spring.application.name=order-management-backend

# PostgreSQL DB config (Render Internal URL)
spring.datasource.url=jdbc:postgresql://dpg-d6vo8ff5r7bs73eu0u7g-a:5432/omsdb_z845
spring.datasource.username=omsdb_z845_user
spring.datasource.password=nuLLBBt7Majehydp8llQ6dHtf7NQbDfw
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Optional (good practice)
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Server port (Render will override, but safe)
server.port=8080